### ISSUE TITLE
"Input vector should be 1-D"

### ISSUE THREAD

**Issue by Projector3567** [sollan/slip_detector#35]
While attempting to extract kinematic parameters using the **extract_parameters** function from **KinematicsFunctions**, I encountered a **ValueError** that says "Input vector should be 1-D". 
I'm using Python 3.11.

1. I loaded .csv file from DLC output for treadmill.
2. I defined speed.
3. When I click extract parameters I get a window pop up with the following error:

Traceback (most recent call last):
  File "...AnalyzeStride.py", line 697, in ExtractParameters
    parameters, pd_dataframe_coords, is_stance, bodyparts = KinematicsFunctions.extract_parameters(...)
  File "...KinematicsFunctions.py", line 733, in extract_parameters
    pairwise_dtw_res_x_5 = pairwise_dtw(toe_xs)
  File "...KinematicsFunctions.py", line 194, in pairwise_dtw
    distance, _ = fastdtw.fastdtw(iterable[i], iterable[j], dist=euclidean)
  File "...site-packages\fastdtw\fastdtw.py", line 53, in fastdtw
    return __fastdtw(x, y, radius, dist)
  [Several recursive calls in fastdtw.py]
  File "...site-packages\fastdtw\fastdtw.py", line 130, in dtw
    return __dtw(x, y, None, dist)
  File "...site-packages\fastdtw\fastdtw.py", line 141, in __dtw
    dt = dist(x[i-1], y[j-1])
  File "...site-packages\scipy\spatial\distance.py", line 536, in euclidean
    return minkowski(u, v, p=2, w=w)
  File "...site-packages\scipy\spatial\distance.py", line 479, in minkowski
    u = _validate_vector(u)
  File "...site-packages\scipy\spatial\distance.py", line 318, in _validate_vector
    raise ValueError("Input vector should be 1-D.")
ValueError: Input vector should be 1-D.

The error originates from the euclidean distance function in scipy.spatial.distance. The euclidean function expects 1-D vectors as input. However, it seems that one or both of the vectors being passed to it are not 1-D. This might be due to the data being processed or perhaps the way the fastdtw function is handling the data.

Any guidance on how to resolve this issue would be greatly appreciated.

**Comment by sollan** [comment]
Please share the following for us to identify the root cause:

1. Header (column names) and a few rows of your raw data (DLC output)
2. A screenshot of the ALMA UI which led up to the error, including all the options you selected before clicking the extract parameters button
3. Your config.yaml

**Comment by Projector3567** [comment]
This is our dataset:
![image](https://github.com/sollan/alma/assets/145003655/0683f1bc-07c7-474d-af2e-e266e80b8dee)

ALMA screenshot:
![image](https://github.com/sollan/alma/assets/145003655/507a5ce1-a261-445b-b7bc-a84767bfc4e3)

Config.yaml:
![image](https://github.com/sollan/alma/assets/145003655/d7e67129-4521-4549-bcff-188193c82d40)

**Comment by sollan** [comment]
Hi! The set-up above looks alright. I wasn't able to replicate the error with the same data format and configurations on an existing installation. 

I would recommend switching to Python 3.8 and see the error disappears, as that's the version proven to work. If the error persists, it could be due to dependencies (and not necessarily `fastdtw` or `scipy`). Please share a copy of your dependency versions in that case for replication.

**Comment by Projector3567** [comment]
[N272_treadmill_30_baselineDLC_resnet50_2023 RtSt KinematicsAug29shuffle1_650000.csv](https://github.com/sollan/alma/files/13486647/N272_treadmill_30_baselineDLC_resnet50_2023.RtSt.KinematicsAug29shuffle1_650000.csv)
I switched to Python 3.8 and managed to get it running. However, I don't receive any output. I am attaching the file I used to try to extract the parameters from.
Thanks a lot.

**Comment by Lyangqian** [comment]
@Projector3567 Hello, I encountered the same issue, and after trying multiple solutions, I discovered that the problem was due to an incompatibility between the versions of `scipy` and `fastdtw`. Once I downgraded the `scipy` version to 1.8.1, the error was resolved.
